# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: node:lts

.image-aws: &image-aws
  image:
    name: rarolabs/aws-cli
    entrypoint: [""]
  services:
    - docker:20.10.15-dind

stages: # List of stages for jobs, and their order of execution
  - setup
  - check-releases
  - check-version
  - quality
  - deploy-rarui
  - publish-release
  - build-storybook
  - publish-storybook
  - deploy-rarui-helper

setup-job:
  stage: setup
  script:
    - printenv
    - yarn install # Instala as dependências com o Yarn
  artifacts:
    paths:
      - node_modules/ # Salva as dependências instaladas como artefatos para uso em etapas subsequentes
  only:
    - merge_requests
check-releases-job:
  stage: check-releases
  script:
    - if [ ! -f releases.json]; then echo "Releases file not found. Run 'yarn build:releases' before merge"; exit 1; fi
  only:
    - merge_requests

check-version-job:
  stage: check-version
  script:
    - git fetch
    - yarn install # Instala as dependências com o Yarn
    - yarn bump:check
  needs:
    - job: setup-job
  only:
    - merge_requests
  except:
    - devel

unit-test-job: # This job runs in the test stage.
  stage: quality # It only starts when the job in the build stage completes successfully.
  script:
    - yarn build:tokens
    - yarn build:icons
    - yarn test:ci
  needs:
    - job: setup-job
    - job: check-version-job
  only:
    - merge_requests

lint-job: # This job also runs in the test stage.
  stage: quality # It can run at the same time as unit-test-job (in parallel).
  script:
    - yarn lint
  needs:
    - job: setup-job
    - job: check-version-job
  only:
    - merge_requests

deploy-rarui-job: # This job runs in the deploy-stable stage.
  stage: deploy-rarui # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - printenv
    - if [ ! -d .yarn/versions ]; then echo "Não há uma versão a ser publicada, abortando deploy."; exit 0; fi
    - yarn install # Instala as dependências com o Yarn
    - yarn bump:check
    - export NODE_OPTIONS="--max_old_space_size=8192"
    - yarn publish:stable
    - |
      curl --location 'https://git.rarolabs.com.br/api/v4/projects/1374/trigger/pipeline' \
        --form token="${TRIGGER_TOKEN}" \
        --form ref="main" \
        --form variables[TRIGGER_JOB]="publish-release"
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "trigger" # Verifica se o evento que acionou a pipeline é um merge request

publish-release-job: # This job runs in the publish-release-job stage.
  stage: publish-release # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - yarn install # Instala as dependências com o Yarn
    - yarn build:tokens
    - yarn build:icons
    - yarn bump:check
    - yarn bump:stable
    - yarn build:docs
    - yarn releases:launch
    - rm -f releases.json
    - git config --global user.email "${GITLAB_USER_NAME}"
    - git config --global user.name "${GITLAB_USER_EMAIL}"
    - git add .
    - git commit -m "ci:🎡 Publish release [skip ci]"
    - git push https://gitlab-ci-token:${PERSONAL_ACCESS_TOKEN}@git.rarolabs.com.br/frontend/rarui.git HEAD:main
    - |
      curl --location 'https://git.rarolabs.com.br/api/v4/projects/1374/trigger/pipeline' \
        --form token="${TRIGGER_TOKEN}" \
        --form ref="main" \
        --form variables[TRIGGER_JOB]="deploy-storybook"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $TRIGGER_JOB == "publish-release"'

build-storybook-job:
  stage: build-storybook # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - printenv
    - yarn install # Instala as dependências com o Yarn
    - yarn build:tokens
    - yarn build:icons
    - yarn build:storybook
    - yarn move:storybook
  artifacts:
    paths:
      - storybook-static/
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $TRIGGER_JOB == "deploy-storybook"'

publish-storybook-job:
  <<: *image-aws
  stage: publish-storybook
  script:
    - amazon-linux-extras install docker
    - aws --version
    - aws ecr get-login-password --region ${AWS_REGION}
    - aws s3 sync storybook-static/ s3://${S3_BUCKET}
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
  needs:
    - job: build-storybook-job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $TRIGGER_JOB == "deploy-storybook"'

deploy-rarui-helper-job:
  stage: deploy-rarui-helper
  script:
    - yarn install # Instala as dependências com o Yarn
    - npm install -g @vscode/vsce
    - cd ./packages/helper
    - yarn bump:stable
    - vsce publish
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $TRIGGER_JOB == "deploy-rarui-helper"'
