changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.spec.{ts,tsx}"
  - "**/*.stories.{ts,tsx}"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs
npmAuthToken: ${NPM_ACCESS_TOKEN:-definir-token-no-npm}
