/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface RaruiTitle {
    as: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    lineclamp: string;
  }
}
declare global {
  interface HTMLRaruiTitleElement
    extends Components.RaruiTitle,
      HTMLStencilElement {}
  var HTMLRaruiTitleElement: {
    prototype: HTMLRaruiTitleElement;
    new (): HTMLRaruiTitleElement;
  };
  interface HTMLElementTagNameMap {
    "rarui-title": HTMLRaruiTitleElement;
  }
}
declare namespace LocalJSX {
  interface RaruiTitle {
    as?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    lineclamp?: string;
  }
  interface IntrinsicElements {
    "rarui-title": RaruiTitle;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "rarui-title": LocalJSX.RaruiTitle &
        JSXBase.HTMLAttributes<HTMLRaruiTitleElement>;
    }
  }
}
