/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariants } from "@rarui/styles";
export { ButtonVariants } from "@rarui/styles";
export namespace Components {
  interface RaruiButton {
    appearance: ButtonVariants["appearance"];
    as: string;
    disabled: HTMLButtonElement["disabled"];
    full: ButtonVariants["full"];
    href: HTMLAnchorElement["href"];
    size: ButtonVariants["size"];
    target: HTMLAnchorElement["target"];
    type: HTMLButtonElement["type"];
    variant: ButtonVariants["variant"];
  }
}
declare global {
  interface HTMLRaruiButtonElement
    extends Components.RaruiButton,
      HTMLStencilElement {}
  var HTMLRaruiButtonElement: {
    prototype: HTMLRaruiButtonElement;
    new (): HTMLRaruiButtonElement;
  };
  interface HTMLElementTagNameMap {
    "rarui-button": HTMLRaruiButtonElement;
  }
}
declare namespace LocalJSX {
  interface RaruiButton {
    appearance?: ButtonVariants["appearance"];
    as?: string;
    disabled?: HTMLButtonElement["disabled"];
    full?: ButtonVariants["full"];
    href?: HTMLAnchorElement["href"];
    size?: ButtonVariants["size"];
    target?: HTMLAnchorElement["target"];
    type?: HTMLButtonElement["type"];
    variant?: ButtonVariants["variant"];
  }
  interface IntrinsicElements {
    "rarui-button": RaruiButton;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "rarui-button": LocalJSX.RaruiButton &
        JSXBase.HTMLAttributes<HTMLRaruiButtonElement>;
    }
  }
}
