/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface RaruiBox {
    as: string;
  }
}
declare global {
  interface HTMLRaruiBoxElement
    extends Components.RaruiBox,
      HTMLStencilElement {}
  var HTMLRaruiBoxElement: {
    prototype: HTMLRaruiBoxElement;
    new (): HTMLRaruiBoxElement;
  };
  interface HTMLElementTagNameMap {
    "rarui-box": HTMLRaruiBoxElement;
  }
}
declare namespace LocalJSX {
  interface RaruiBox {
    as?: string;
  }
  interface IntrinsicElements {
    "rarui-box": RaruiBox;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "rarui-box": LocalJSX.RaruiBox &
        JSXBase.HTMLAttributes<HTMLRaruiBoxElement>;
    }
  }
}
