/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface RaruiText {
    as: "p" | "span";
    lineClamp: string;
  }
}
declare global {
  interface HTMLRaruiTextElement
    extends Components.RaruiText,
      HTMLStencilElement {}
  var HTMLRaruiTextElement: {
    prototype: HTMLRaruiTextElement;
    new (): HTMLRaruiTextElement;
  };
  interface HTMLElementTagNameMap {
    "rarui-text": HTMLRaruiTextElement;
  }
}
declare namespace LocalJSX {
  interface RaruiText {
    as?: "p" | "span";
    lineClamp?: string;
  }
  interface IntrinsicElements {
    "rarui-text": RaruiText;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "rarui-text": LocalJSX.RaruiText &
        JSXBase.HTMLAttributes<HTMLRaruiTextElement>;
    }
  }
}
