/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface RaruiTabsItem {
    label: string;
  }
}
declare global {
  interface HTMLRaruiTabsItemElement
    extends Components.RaruiTabsItem,
      HTMLStencilElement {}
  var HTMLRaruiTabsItemElement: {
    prototype: HTMLRaruiTabsItemElement;
    new (): HTMLRaruiTabsItemElement;
  };
  interface HTMLElementTagNameMap {
    "rarui-tabs-item": HTMLRaruiTabsItemElement;
  }
}
declare namespace LocalJSX {
  interface RaruiTabsItem {
    label?: string;
  }
  interface IntrinsicElements {
    "rarui-tabs-item": RaruiTabsItem;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "rarui-tabs-item": LocalJSX.RaruiTabsItem &
        JSXBase.HTMLAttributes<HTMLRaruiTabsItemElement>;
    }
  }
}
