name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: yarn

      - name: Save node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

  check-version:
    runs-on: ubuntu-latest
    needs: setup # Only runs after the 'setup' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch latest commits
        run: git fetch

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Check version bump
        run: yarn bump:check

  check-releases:
    runs-on: ubuntu-latest
    needs: check-version # Only runs after the 'check-version' job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check releases
        run: |
          if [ ! -f releases.json ]; then 
            echo "Releases file not found. Run 'yarn build:releases' before merge";
            exit 1;
          fi

  unit-test:
    runs-on: ubuntu-latest
    needs: [check-version, check-releases] # Only runs after the 'check-version, check-releases' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Setup dependencies
        run: yarn setup

      - name: Run unit tests
        run: yarn test:ci

  lint:
    runs-on: ubuntu-latest
    needs: [check-version, check-releases] # Only runs after the 'check-version, check-releases' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Run lint
        run: yarn lint

  checklist-comment:
    runs-on: ubuntu-latest
    needs: [unit-test, lint] # Only runs after the 'unit-test, lint' job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./.github/resources/checklist.txt
          comment_tag: execution
